"""empty message

Revision ID: 7dcfb20ba92d
Revises: 
Create Date: 2019-06-03 16:43:22.277991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcfb20ba92d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slackEmpLeaves',
    sa.Column('uUid', sa.INTEGER(), nullable=False),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=False),
    sa.Column('daysCount', sa.INTEGER(), nullable=False),
    sa.Column('leaveType', sa.VARCHAR(length=15), nullable=False),
    sa.Column('rawComment', sa.TEXT(), nullable=True),
    sa.Column('slackEmailAddress', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slackUsername', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackUserId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackChannelId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackTeamId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackFullName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slackAvatarUrl', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uUid'),
    sa.UniqueConstraint('uUid')
    )
    op.create_table('slackOAuth',
    sa.Column('uUid', sa.INTEGER(), nullable=False),
    sa.Column('authScope', sa.TEXT(), nullable=False),
    sa.Column('accessToken', sa.TEXT(), nullable=False),
    sa.Column('slackTeamId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackTeamName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slackUserId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackAuthChannelId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackAuthChannel', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slackWebHookUrl', sa.TEXT(), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uUid'),
    sa.UniqueConstraint('uUid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slackOAuth')
    op.drop_table('slackEmpLeaves')
    # ### end Alembic commands ###
