"""empty message

Revision ID: 82e5266d820e
Revises: b470a0e058c9
Create Date: 2019-02-19 00:35:58.581500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e5266d820e'
down_revision = 'b470a0e058c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slackEmpLeaves', 'slackEnterpriseId')
    op.create_unique_constraint(None, 'slackOAuth', ['uUid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slackOAuth', type_='unique')
    op.add_column('slackEmpLeaves', sa.Column('slackEnterpriseId', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
