"""empty message

Revision ID: b470a0e058c9
Revises: b5c9f7e8fe80
Create Date: 2019-02-16 13:25:24.190349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b470a0e058c9'
down_revision = 'b5c9f7e8fe80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slackOAuth',
    sa.Column('uUid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('authScope', sa.TEXT(), nullable=False),
    sa.Column('accessToken', sa.TEXT(), nullable=False),
    sa.Column('slackTeamId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackTeamName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slackUserId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackAuthChannelId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackAuthChannel', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slackWebHookUrl', sa.TEXT(), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uUid'),
    sa.UniqueConstraint('uUid')
    )
    op.create_unique_constraint(None, 'slackEmpLeaves', ['uUid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slackEmpLeaves', type_='unique')
    op.drop_table('slackOAuth')
    # ### end Alembic commands ###
