"""empty message

Revision ID: b5c9f7e8fe80
Revises: 
Create Date: 2019-02-16 09:23:41.365317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5c9f7e8fe80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slackEmpLeaves',
    sa.Column('uUid', postgresql.INTEGER(), nullable=False),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=False),
    sa.Column('daysCount', sa.INTEGER(), nullable=False),
    sa.Column('leaveType', sa.VARCHAR(length=15), nullable=False),
    sa.Column('rawComment', sa.TEXT(), nullable=True),
    sa.Column('slackEmailAddress', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slackUsername', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackUserId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackChannelId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackTeamId', sa.VARCHAR(length=15), nullable=False),
    sa.Column('slackEnterpriseId', sa.VARCHAR(length=15), nullable=True),
    sa.Column('slackFullName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slackAvatarUrl', sa.TEXT(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uUid'),
    sa.UniqueConstraint('uUid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slackEmpLeaves')
    # ### end Alembic commands ###
